import type { Metadata } from "next";
import { Fondamento } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Providers from "./components/Providers";


const fondamento = Fondamento({ subsets: ["latin"], 
variable: '--font-fondamento', 
weight: ['400'] });

export const metadata: Metadata = {
  title: "SK Portfolio",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={`${fondamento.className} bg-slate-50 text-black dark:bg-slate-900 dark:selecton:bg-slate-900
        dark:text-white h-full selection:bg-slate-100`}>
        <Providers>
        <Navbar/>
        {children}
        </Providers>
        </body>
    </html>
  );
}
